# serverless.yml
service: apollo-lambda
# app and org for use with dashboard.serverless.com
app: podmix
org: cartertune

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x
functions:
  graphql:
    handler: build/app.graphqlHandler
    environment:
      MONGO_DB_URI: ${file(./config.${self:provider.stage}.json):MONGO_DB_URI, ${self:provider.stage}}
      KEY_ISSUER: ${file(./config.${self:provider.stage}.json):KEY_ISSUER, ${self:provider.stage}}
      PM_AWS_REGION: ${file(./config.${self:provider.stage}.json):PM_AWS_REGION, ${self:provider.stage}}
      S3_BUCKET_NAME: ${file(./config.${self:provider.stage}.json):S3_BUCKET_NAME, ${self:provider.stage}}
      PM_AWS_KEY_ID: ${file(./config.${self:provider.stage}.json):PM_AWS_KEY_ID, ${self:provider.stage}}
      PM_AWS_SECRET_KEY: ${file(./config.${self:provider.stage}.json):PM_AWS_SECRET_KEY, ${self:provider.stage}}
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cores: true
plugins:
  - serverless-offline
custom:
  serverless-offline:
    port: 3000
